#!/bin/sh

ERL_PATH=ebin

CONFIG=syncserver.config

SNAME="syncserver@$(uname -n)"

APPLIST='[sasl,mnesia,syncserver]'

START_SCRIPT="
	Node='$SNAME',
	io:format(\"Starting Syncserver on node ~p..~n\",[Node]),
	lists:foreach(fun(A)->
			io:format(\"Starting application ~p.. \",[A]),
			SR=application:start(A),
			io:format(\"~p~n\",[SR]),
			ok=SR
			end, $APPLIST),
	io:format(\"Syncserver started~n\",[])."

STOP_SCRIPT="
	Node='$SNAME',
	io:format(\"Stopping Syncserver on node ~p..~n\",[Node]),
	lists:foreach(fun(A)->
			io:format(\"Stopping application ~p.. \",[A]),
			SR=rpc:call(Node,application,stop,[A]),
			io:format(\"~p~n\",[SR])
			end, lists:reverse($APPLIST)),
	io:format(\"Shutdown node ~p.. \",[Node]),
	R=rpc:call(Node,init,stop,[]),
	io:format(\"~p~n\",[R]),
	io:format(\"Shutdown this node~n\",[]),
	init:stop()."

ERL_OPTIONS="-detached  -pa $ERL_PATH -sname $SNAME -config $CONFIG -noshell "
ERL_OPTIONS_SHELL="-pa $ERL_PATH -sname $SNAME"

case $1 in
	start) 
	    exec erl ${ERL_OPTIONS} -config $CONFIG -eval "$START_SCRIPT"
	;;
	start-shell) 
	    exec erl ${ERL_OPTIONS_SHELL} -eval "$START_SCRIPT"
	;;
	stop)
	    exec erl -noshell -sname 'stop-syncserver' -eval "$STOP_SCRIPT"
	;;
	*)
	    echo 'Usage:'
	    echo ' ./syncserver start'
	    echo ' ./syncserver start-shell'
	    echo ' ./syncserver stop'
	;;
esac
